### ISSUE TITLE
How to build on Windows?

### ISSUE THREAD

**Issue by theseyan** [fails-components/webtransport#43]
Hi, I'm very excited to try out this project but I can't seem to succeed in building this on Windows. I've installed CMake, Perl, Ninja and other dependencies, but to no avail.
Any specific instructions?

**Comment by martenrichter** [comment]
Unfortunately not. I am also developing on windows, but I run the project in a WSL Docker container since building on windows is not possible.
Reason are the following:
1.) There some tiny adjustments in the code necessary for windows, but this is doable.
2.) The biggest problem is that cmake.js is using msvc and some of the libraries requires the clang compiler. And I did not find a way to change this. This is the point where I got stuck, when I tried to port it to window.
Of course, if you or some else finds a solution of the problem, I will be happy to add 1. Since it will also simplify my development workflow, and may be enable it for other projects.

**Comment by theseyan** [comment]
Thanks for the clarification. I've succeeded in building it on Debian, but is there a way to cross compile it for Windows? Maybe using mingw-w64?

**Comment by martenrichter** [comment]
Maybe, but I have not tried it; it probably needs modifications....; it is not on my agenda, though...

**Comment by martenrichter** [comment]
And here is the branch where my previous attempts to include windows are stored:
https://github.com/fails-components/webtransport/tree/windows
At least I found a switch to go to clang, but it collides with another issue, when vcpkg needed for protobuf is installed:

**Comment by martenrichter** [comment]
OK, some further progress. I can now compile more.
However poll server needs modifications...
But the upstream lib plans to replace the epoll server with something more portable:
https://github.com/google/quiche/commit/e48e609f9d3bb2d659191bce18813c17e9ff9e81
So I will wait with the windows stuff until this aspect is changed in the lib, and I have to rewrite it anyway.

**Comment by martenrichter** [comment]
Finally, thanks also to progress on the event loop with libevent on the upstream library quiche, on the branch https://github.com/fails-components/webtransport/tree/windows, it compiles and passes the units test. So you might want to give it a try. Merging with the master branch and also a release may happen soon.

**Comment by martenrichter** [comment]
Now moved to the development branch
https://github.com/fails-components/webtransport/tree/development
currently missing CI tests are blocking the release.

**Comment by theseyan** [comment]
Amazing work, Marten! I've succeeded in building on Windows with the latest development branch, and all tests have passed.

**Comment by martenrichter** [comment]
Perfect, I will go ahead and release a new version. The only annoying thing are the build times on windows, so I put pre-compiled binaries on my to-do list.

**Comment by theseyan** [comment]
As a side note, CMake on Windows targets the MSVC C and C++ compilers by default which don't succeed in building. I had to specifically ask CMake to use Clang using `cmake-js build -t ClangCL` which did it. Also, GnuWin32 zlib throws an error looking for `unistd.h` which can be solved using [this SO answer](https://stackoverflow.com/a/24417661/7189950).

Also yeah, I think the package should include pre-compiled binaries for major targets (x86,64 for windows, linux) and ARM (I can help with ARM if you need it).

**Comment by martenrichter** [comment]
Yes, this with cmake-js is know. But there is actually a script in place, if you use `npm install`, or `npm run build-debug` or `npm run rebuild-debug` etc. .
I do not get the problem with the `unistd.h`, but I am using VS C++ 2019 build, maybe this is the reason?

Regarding ARM I do not think a GitHub runner is available for unit tests. But precompiling is an option, if you need ARM support, necessary modifications and instructions for cross-compiling are appreciated.

**Comment by martenrichter** [comment]
Precompiled binaries for Windows, Linux, and macOS are coming with version `0.0.5` (the final builds are running. But only for the platforms supported by the GitHub runners, so mainly intel 64-bit (for windows also 32-bit). 
If someone needs other architectures, it will need cross-compiling in `https://github.com/fails-components/webtransport/blob/master/.github/workflows/publish-packages.yml`, I have no plans to do this, but if someone supplies a PR I am open.
Note the new version is a partial rewrite. Since I use now napi instead of nan, to have fewer precompiler runs.
